[project]
name = "swu-rules-qa"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Grant Wasil", email = "grantwasil1@gmail.com" }
]
dependencies = []
readme = "README.md"
requires-python = ">= 3.8"

[tool.rye]
managed = true
virtual = true
dev-dependencies = []
